apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deploy.yaml
  # - deploy-frontend.yaml  # Frontend (DISABLED)
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - ghcr-secret-external.yaml
