---
apiVersion: v1
kind: Service
metadata:
  name: nima-api
  namespace: nima
  labels:
    app: nima
    component: api
spec:
  type: ClusterIP
  selector:
    app: nima
    component: api
  ports:
    - port: 8000
      targetPort: 8000
      name: http

