apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - bind-configmap.yaml
  - dnsmasq-upstream-configmap.yaml
  - deployment.yaml
  - service.yaml
  - bind-service.yaml
  - ingress.yaml
