---
all:
  children:
    raspberry_pi:
      hosts:
        node-0:
          ansible_host: node-0.local
          ansible_user: raolivei
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        node-1:
          ansible_host: node-1.local
          ansible_user: raolivei
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        eldertree:
          ansible_host: eldertree.local
          ansible_user: raolivei
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
