---
all:
  children:
    raspberry_pi:
      hosts:
        node-0.eldertree.local: # Control plane node
          ansible_host: 192.168.2.86
          poe_hat_enabled: true
        node-1.eldertree.local: # Worker node
          ansible_host: 192.168.2.85
          poe_hat_enabled: true
