---
all:
  children:
    raspberry_pi:
      hosts:
        node-0:
          ansible_host: 192.168.2.86
          ansible_user: raolivei
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          ansible_ssh_pass: "ac0df36b52"
          node_ip: "192.168.2.86"
          node_hostname: "node-0"
        node-1:
          ansible_host: 192.168.2.85
          ansible_user: raolivei
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          ansible_ssh_pass: "ac0df36b52"
          node_ip: "192.168.2.85"
          node_hostname: "node-1"
