---
all:
  children:
    raspberry_pi:
      vars:
        ansible_user: raolivei
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519_raolivei
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_python_interpreter: /usr/bin/python3
        poe_hat_enabled: true
      hosts:
        node-1:
          ansible_host: 192.168.2.101
        node-2:
          ansible_host: 192.168.2.102
        node-3:
          ansible_host: 192.168.2.103
