---
all:
  children:
    raspberry_pi:
      hosts:
        node-0:
          ansible_host: 192.168.2.86
          ansible_user: raolivei
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_raolivei
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          ansible_python_interpreter: /usr/bin/python3
          poe_hat_enabled: true
        node-1:
          ansible_host: 192.168.2.85
          ansible_user: raolivei
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_raolivei
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          ansible_python_interpreter: /usr/bin/python3
          poe_hat_enabled: true
