apiVersion: v1
kind: Secret
metadata:
  name: pihole-scrape-config
  namespace: observability
type: Opaque
stringData:
  pihole-scrape.yaml: |
    - job_name: 'pihole'
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      static_configs:
        - targets:
          - 'pi-hole.pihole.svc.cluster.local:9617'
          labels:
            service: pihole
            namespace: pihole

