---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pushgateway
  namespace: observability
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: traefik
  rules:
    - host: pushgateway.eldertree.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: observability-monitoring-stack-prometheus-pushgateway
                port:
                  number: 9091
  tls:
    - hosts:
        - pushgateway.eldertree.local
      secretName: pushgateway-tls
