apiVersion: v2
name: flux-ui
description: Flux UI (Weave GitOps) for visualizing and managing FluxCD deployments
type: application
version: 0.1.0
appVersion: "2.0.0"
dependencies:
  - name: gitops-server
    version: "2.0.0"
    repository: oci://ghcr.io/weaveworks
    alias: weave-gitops
    condition: weave-gitops.enabled
