apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml # prometheus-community Helm repository
  - helmrelease.yaml # kube-prometheus-stack (Prometheus + Grafana + Alertmanager)
