apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - externalsecret.yaml
  - ghcr-secret-external.yaml
  - pvc.yaml
  - configmap.yaml
  - skills-configmap.yaml
  - deployment.yaml
  - ingress.yaml
