apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Autoscaling infrastructure
resources:
  - keda # Kubernetes Event-Driven Autoscaling (horizontal)
  - vpa  # Vertical Pod Autoscaler (vertical)







