apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - audio-pvc.yaml
  - audio-nginx-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - audio-service.yaml
  - audio-ingress.yaml


