apiVersion: v1
kind: Service
metadata:
  name: eldertree-docs
  namespace: eldertree-docs
  labels:
    app.kubernetes.io/name: eldertree-docs
    app.kubernetes.io/component: documentation
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: eldertree-docs
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP


