---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: swimto-updates
  namespace: swimto
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux Image Automation
        email: flux-image-automation@eldertree.local
      messageTemplate: |
        Update swimto images to {{range .Updated.Images}}{{println .}}{{end}}
        
        Automated image update by Flux
    push:
      branch: main
  update:
    strategy: Setters
    setters:
      - paths:
          - spec.template.spec.containers.[name=api].image
          - spec.template.spec.containers.[name=web].image
        value: '{{ .Image }}'

