{{- range $name, $es := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  namespace: {{ include "eldertree-app.namespace" $ }}
spec:
  refreshInterval: {{ $es.refreshInterval | default "24h" }}
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ $es.targetName | default $name }}
    creationPolicy: Owner
    {{- if $es.template }}
    template:
      {{- if $es.type }}
      type: {{ $es.type }}
      {{- end }}
      {{- if $es.engineVersion }}
      engineVersion: {{ $es.engineVersion }}
      {{- end }}
      {{- with $es.template }}
      data:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  data:
    {{- range $es.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
    {{- end }}
{{- end }}
