apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pitanga
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/eldertree/pitanga
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: pitanga-website
      namespace: pitanga
