---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canopy
  namespace: canopy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: canopy-redirect-https@kubernetescrd,canopy-canopy-basic-auth@kubernetescrd
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  labels:
    app: canopy
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - canopy.eldertree.local
      secretName: canopy-tls
  rules:
    - host: canopy.eldertree.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: canopy-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: canopy-frontend
                port:
                  number: 3000
