---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canopy
  namespace: canopy
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  labels:
    app: canopy
spec:
  tls:
  - hosts:
    - canopy.eldertree.local
    secretName: canopy-tls
  rules:
  - host: canopy.eldertree.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canopy-frontend
            port:
              number: 3000

