apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eldertree-audio

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - static-content.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
