apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
  annotations:
    # Tell MetalLB to ignore this service so K3s ServiceLB (Klipper) can take it
    metallb.universe.tf/address-pool: ""
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  externalTrafficPolicy: Cluster
  ports:
    - name: dns-udp
      port: {{ .Values.service.dnsUdpPort }}
      protocol: UDP
      targetPort: 53
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.dnsNodePort }}
      nodePort: {{ .Values.service.dnsNodePort }}
      {{- end }}
    - name: dns-tcp
      port: {{ .Values.service.dnsTcpPort }}
      protocol: TCP
      targetPort: 53
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.dnsNodePort }}
      nodePort: {{ .Values.service.dnsNodePort }}
      {{- end }}
  selector:
    {{- include "pi-hole.selectorLabels" . | nindent 4 }}

