apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: personal-website
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/eldertree/personal-website
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: personal-website
      namespace: personal-website
