{{- if and .Values.swimto.enabled .Values.swimto.web.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: swimto-web-scaler
  namespace: swimto
  labels:
    {{- include "keda-scaledobjects.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: swimto-web
  minReplicaCount: {{ .Values.swimto.web.minReplicas }}
  maxReplicaCount: {{ .Values.swimto.web.maxReplicas }}
  pollingInterval: {{ .Values.global.pollingInterval }}
  cooldownPeriod: {{ .Values.global.cooldownPeriod }}
  triggers:
{{- if eq (.Values.swimto.web.triggerType | default "cpu-memory") "http-rate" }}
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.global.prometheus.serverAddress }}
        metricName: http_requests_per_second
        threshold: {{ .Values.swimto.web.httpRateThreshold | default "10" | quote }}
        query: |
          sum(rate(traefik_service_requests_total{
            service="swimto-web-service",
            namespace="swimto"
          }[2m]))
{{- else }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ .Values.global.cpuThreshold | quote }}
    - type: memory
      metricType: Utilization
      metadata:
        value: {{ .Values.global.memoryThreshold | quote }}
{{- end }}
{{- end }}

