{{- if and .Values.swimto.enabled .Values.swimto.web.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: swimto-web-scaler
  namespace: swimto
  labels:
    {{- include "keda-scaledobjects.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: swimto-web
  minReplicaCount: {{ .Values.swimto.web.minReplicas }}
  maxReplicaCount: {{ .Values.swimto.web.maxReplicas }}
  pollingInterval: {{ .Values.global.pollingInterval }}
  cooldownPeriod: {{ .Values.global.cooldownPeriod }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ .Values.global.cpuThreshold | quote }}
    - type: memory
      metricType: Utilization
      metadata:
        value: {{ .Values.global.memoryThreshold | quote }}
{{- end }}

